version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6 # Invoke the Heroku orb

workflows:
  test-build-deploy:
    jobs:
      - test
      # - build:
      #     requires: 
      #       - test
      # - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only:
      #           - main

jobs:
  test:         
    docker:
      - image: cimg/node:17.5.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm test
      - run:
          name: production-build
          command: npm run build
      
  # build:
  #   docker:
  #     - image: cimg/node:17.5.0
  #   steps: 
  #     - checkout     
  #     - run:
  #         name: production-build
  #         command: npm run build